-- Create Products Table
CREATE TABLE IF NOT EXISTS public.products (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  category text NOT NULL,
  price numeric NOT NULL,
  stock integer NOT NULL,
  sold integer DEFAULT 0,
  badge text,
  image text,
  description text,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Create Orders Table
CREATE TABLE IF NOT EXISTS public.orders (
  id text PRIMARY KEY,
  customer text NOT NULL,
  email text NOT NULL,
  phone text,
  product text,
  category text,
  amount numeric NOT NULL,
  quantity integer NOT NULL,
  status text DEFAULT 'Pending'::text,
  date date DEFAULT CURRENT_DATE NOT NULL,
  address text,
  shipping text,
  payment text DEFAULT 'Unpaid'::text,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Create Customers Table
CREATE TABLE IF NOT EXISTS public.customers (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  email text UNIQUE NOT NULL,
  phone text,
  city text,
  orders integer DEFAULT 1 NOT NULL,
  spent numeric DEFAULT 0 NOT NULL,
  joined date DEFAULT CURRENT_DATE NOT NULL,
  status text DEFAULT 'Active'::text,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS (Row Level Security) if desired, or keep it open for simple admin panels.
-- Since the service key will be used on the server side, it bypasses RLS policies.
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.customers ENABLE ROW LEVEL SECURITY;

-- Simple policies to allow reading/writing
CREATE POLICY "Allow read access to products" ON public.products FOR SELECT USING (true);
CREATE POLICY "Allow read access to orders" ON public.orders FOR SELECT USING (true);
CREATE POLICY "Allow read access to customers" ON public.customers FOR SELECT USING (true);
